### ISSUE TITLE
Add OpenTelemetry support for honeycomb

### ISSUE THREAD

**Issue by jfhbrook-at-work** [entropic-dev/boltzmann#100]
We would like to add OpenTelemetry support for the honeycomb tracing feature in boltzmann. It's a bit of a bear - a lot of moving parts - so I wanted to capture a loose list of stuff I need to do to make this work.

- [X] Ensure tests pass on latest
- [ ] Add `Sdk#start` init call/boilerplate near top of bundle
  - [x] Peruse the boltzmann bundle generated today and identify a place to inject the calls - this is probably entrypoint.ts but the call has to happen "early" so there's some risk here
  - [x] Find a good way to hook onto the Promise returned by `Sdk#start` - this is likely a module-scoped variable
  - [x] Run tests to ensure this isn't exploding
  - [ ] Add a new test to ensure startup is behaving
- [ ] Do whatever the rough equivalent of `startTrace` is for otel in the `honeycombTrace` middleware - this is probably pre-populating the active context and creating a parent span
  - [ ] Extract metadata fields from request and response - the same fields are passed to the initialized trace in the beeline instrumentation, but they'll be added to the active context
  - [ ] Investigate trace parent related request headers and ensure they're plumbed in
  - [ ] Convince myself that the calls are being made after the SDK is started
  - [ ] Convince myself that the active Context is in a healthy state
  - [ ] Ensure current tests are passing
  - [ ] Add a new test that covers the new functionality
- [ ] Create/close a span in the `honeycombMiddleSpans` middleware
  - [ ] Create a child span, following the express auto-instrumentation example
  - [ ] Add the same metadata fields as beelines do today
  - [ ] Convince myself that the active Context is in a good state, etc
  - [ ] Ensure current tests are passing
  - [ ] Add a new test that covers the new functionality
- [ ] (**TK**) Develop an integration test plan
- [ ] (**TK**) Actually *do* the integration test plan
- [ ] (**TK**) Prepare for a release
- [ ] (**TK**) Actually do the release

**Comment by ericsampson** [comment]
- "Create a top-level trace in the top-level middleware"
    - s/trace/span :)
- "Extract metadata fields from request and response"
    - The fields should use the [OTel semantic convention names](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) instead of whatever it was doing before. This lights up certain behavior in Honeycomb and other OTel back-ends.
- I'm curious why we're creating a second child span in the middleware, maybe I'd need to see it to understand. I wonder if `span events` are better for this. They didn't exist when the beelines were written.
- **Additional item**: boltzmann should expose a way for application authors to make relevant SDK calls such as `addContext()`. Consider what we want to expose to the app authors, the current `context` object so that people can make method calls from it? And the `span` object so that people can make their own child spans? etc

**Comment by jfhbrook-at-work** [comment]
> s/trace/span :)

Good catch, that was a typo on my part. Yeah, I want to create a top-level span.

> The fields should use the OTel semantic convention names instead of whatever it was doing before.

Oh awesome, that resource will come in handy! Thanks!

> I'm curious why we're creating a second child span in the middleware

I could be misinterpreting things - I'm having a lot of struggles mapping what the beelines do today with what we want otel to do tomorrow. But here, I'll show you what I'm looking at and you can tell me if it reads the same to you.

The honeycomb middleware module exposes two middlewares: one called `honeycombTrace` and another called `honeycombMiddlewareSpans`.

The `honeycombTrace` middleware creates a beeline trace:

https://github.com/entropic-dev/boltzmann/blob/latest/templates/boltzmann/middleware/honeycomb.ts#L25-L40

We've talked about this before and I keep going in circles about it, but:

1. There's no strict analog to creating a trace in otel - instead, it appears that if you start the SDK then you have an importable `trace` object.
2. Up to this point I thought I needed to create a parent span, but now I'm wondering if the rough equivalent is actually updating the active Context?

The `honeycombMiddlewareSpans` middleware explicitly creates beeline spans:

https://github.com/entropic-dev/boltzmann/blob/latest/templates/boltzmann/middleware/honeycomb.ts#L113-L121

What I had in my list of tasks is a reflection of the plan to create a span in `honeycombTrace`, and then another span in `honeycombMiddlewareSpans`. But if what I have to do instead of creating the `honeycombTrace` span is to update the active Context, then there is no parent span - it's initializing the context, and then creating just the one span.

Does this make sense? Do you think the rough analog to the `honeycombTrace` middleware step is populating the Context? Do you think I need to create a span there?

> Additional item: boltzmann should expose a way for application authors to make relevant SDK calls such as addContext(). 

Good call. I don't know what this looks like, but it certainly warrants investigation. One idea is to have people import/use the otel abstractions, but given how clunky and confusing this API is (maybe a personal problem) maybe a proper facade or two is a good idea? I'll add this to the task list either way.

**Comment by ericsampson** [comment]
so the equivalent of `honeycombTrace` in OTel will look like this example. Forget about the term 'trace', you're just confusing yourself. You will need to explicitly start a top-level span just like this example:
https://opentelemetry.io/docs/instrumentation/js/api/tracing/#describing-a-span
 (note also how it uses the exported `SemanticAttributes.HTTP_METHOD` stuff instead of hardcoding strings from that link I posted above. This is a better approach)
 
Maybe that's a good place to get working first, and then we can work on the middleware spans after.
For child spans, you either A) need access to the parent span object in order to do [something like this](https://github.com/open-telemetry/opentelemetry-js/blob/main/examples/otlp-exporter-node/tracing.js):
```
const ctx = tracer.setSpan(context.active(), parent_span);
const child_span = tracer.startSpan('doWork', undefined, ctx);
```
or B) use the fancier `context.with(...)` method as shown in the example in the link above, to create a closure so that the inner `startSpan()` automagically has the context and so creates a child span.

Don't forget that the spans have to be `.end()` as well, even if errors happen.

**Comment by jfhbrook-at-work** [comment]
OK, so it looks like my understanding around needing a parent and child span (I keep saying trace on accident but I really do mean span!!) is the right idea. I'll move forward with it and see what shakes out. Thanks!
